pages:
  image: node:lts
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm ci
    - npm run build
    # GitLab Pages espera los archivos en una carpeta 'public'.
    # Limpiamos si hay algo y movemos la salida 'dist' de Astro a 'public'
    - rm -rf public
    - cp -r dist public

  artifacts:
    paths:
      - public
